version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cwave_pc_cafe_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cwave_pc_cafe_nintendo
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d     # MySQL 설정 파일
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always